#!/usr/bin/env sh
#
# A rofi powered menu to execute power related action.
# Uses: poweroff reboot rofi

power_off=' Shutdown'
reboot=' Restart'
lock=' Lock'

chosen=$(printf '%s;%s;%s\n' "$power_off" "$reboot" "$lock" \
    | rofi -dmenu \
           -sep ';' \
           -p "Select" \
           -i \
           -selected-row 2)

case "$chosen" in
    "$power_off")
        poweroff
        ;;

    "$reboot")
        reboot
        ;;

    "$lock")
        betterlockscreen -l dimblur
        ;;

    *) exit 1 ;;
esac
