#!/usr/bin/bash
#
# A rofi powered menu to execute power related action.
# Uses: poweroff reboot rofi

power_off=' Shutdown'
reboot=' Restart'
lock=' Lock'
suspendd=' Suspend'

chosen=$(printf '%s;%s;%s;%s\n' "$power_off" "$reboot" "$lock" "$suspendd" \
    | rofi -dmenu \
           -sep ';' \
           -p "Select" \
           -i \
           -selected-row 1)

case "$chosen" in
    "$power_off")
        poweroff
        ;;

    "$reboot")
        reboot
        ;;

    "$lock")
        betterlockscreen -l dimblur
        ;;
    "$suspendd")
        systemctl suspend
        ;;

    *) exit 1 ;;
esac
